### ISSUE TITLE
Enhance documentation in README.MD & index.js file.

### ISSUE THREAD

**Issue by manishraj27** [manishraj27/mern-project-cli#1]
Update the documentation.

**Comment by kidobop** [comment]
hey what changes are you expecting in the documentation?

**Comment by manishraj27** [comment]
Enhancing the readme.md and providing comments for the code.

Also you can raise other issues as well!

And if you like the tool consider giving a star!

**Comment by pchy-ynda** [comment]
> Enhancing the readme.md and providing comments for the code.
> 
> Also you can raise other issues as well!
> 
> And if you like the tool consider giving a star!

Hello, if no one is currently working on this issue, can you please assign me under the Hacktoberfest tag?

**Comment by manishraj27** [comment]
Go ahead! @pchy-ynda
