### ISSUE TITLE
[Bug]: Default Title 'Vite + React' Displayed in Browser Tab and Favicon Not Updated

### ISSUE THREAD

**Issue by MuhammadAshraf23** [manishraj27/mern-project-cli#3]
### Description:
The browser tab currently shows the default title "Vite + React," and the website is using the default Vite favicon. These should be updated to a more meaningful title and favicon that better represent the project's identity.

### Steps to Reproduce:

Open the website in a browser.
Observe the title displayed in the browser tab as "Vite + React."
Notice the favicon is the default Vite icon.
### Expected Behavior:
The website title should reflect the project's name, and the favicon should be customized to match the project's branding.

### Actual Behavior:
The browser tab displays the default title "Vite + React," and the favicon remains the Vite default.

### Suggestions for improvements:

Update the title to the project's actual name for better identification.
Replace the default favicon with one that matches the project's branding (e.g., logo or a custom icon).

**Comment by manishraj27** [comment]
Since website is a private repo, I cant assign you the task but surely update it.

**Comment by manishraj27** [comment]
Consider raising issues in the current repo!
