### ISSUE TITLE
The stats are not aligned in mobile view

### ISSUE THREAD

**Issue by shreyansh1410** [manishraj27/mern-project-cli#5]
![image](https://github.com/user-attachments/assets/108a9626-dbeb-41b8-8a49-03def819f55d)

**Comment by manishraj27** [comment]
https://github.com/manishraj27/mern-project-cli-website
submit the pr here!

**Comment by shreyansh1410** [comment]
I don't understand, should I open this issue there?

**Comment by shreyansh1410** [comment]
Is that also a part of Hacktoberfest?

**Comment by manishraj27** [comment]
No it's not!
