### ISSUE TITLE
Add the option to create a next js appilcation

### ISSUE THREAD

**Issue by mdrehan369** [manishraj27/mern-project-cli#6]

**Comment by mdrehan369** [comment]
Please assign this issue to me under hactoberfest. It would be a great oppurtunity for me

**Comment by manishraj27** [comment]
Go ahead!

1. make sure you keep the code clean and you make a new file under commands folder named createNextJs.js and import the command in index.js
2. write your code similar to other commands structure
3. the command should be devcli create <project_name> --nextjs [nextjs should be in option with devcli create]
4. also does this also create backend structure as well?

**Comment by mdrehan369** [comment]
Yes it will create a backend structure also

**Comment by manishraj27** [comment]
Ok then, raise the pr
